### ISSUE TITLE
Add time estimation to mutagen energy progress bar

### ISSUE THREAD

**Issue by erezesk** [erosson/swarm#352]
Hey, 

Currently there is no time estimation on the amount of energy left for Ascending.
Could you add it please?

![screen shot 2015-02-19 at 6 55 00 pm](https://cloud.githubusercontent.com/assets/714860/6271360/dbd6d99e-b868-11e4-8807-28076b243aa9.png)

I might add a PR later

Erez

**Comment by erosson** [comment]
Thanks for reporting this! Code for this was already there, but it broke a short time back and I never noticed. Fixed.

Added a more precise format for the estimate while I'm looking at it. I'm hesitating on this elsewhere because meat estimates are wrong #304, but energy doesn't have that problem.

> I might add a PR later

Too slow, but thanks anyway!
